### ISSUE TITLE
UploadFileCallback onComplete should pass File also

### ISSUE THREAD

**Issue by adevezin** [Storj/android-libstorj#10]
The UploadFileCallback's onComplete method should pass a Storj File also with a String filepath. This will allow for things to be done with the file after it is uploaded. Where as just passing a filepath would not allow the app to know any further information about the file that was uploaded

**Comment by kaloyan-raev** [comment]
Agree. It will be easy to pass the ID of the Storj File at least. I'll try to modify libstorj to return a complete File object with all metadata.

**Comment by kaloyan-raev** [comment]
https://github.com/Storj/libstorj/pull/410

**Comment by kaloyan-raev** [comment]
Implemented in version 0.3.
