### ISSUE TITLE
Pass string instead of file into download

### ISSUE THREAD

**Issue by dri94** [Storj/android-libstorj#12]
Since the Storj Bridge api only seems to need the file id. We should have the method for downloading reflect such and just request the file id instead of the whole file.

**Comment by kaloyan-raev** [comment]
Sure. I will add variants of the API methods that require only bucket id and file id strings instead of complete Bucket and File objects.

**Comment by dri94** [comment]
Awesome!

**Comment by kaloyan-raev** [comment]
Implemented in version 0.3.
