### ISSUE TITLE
Specify path for downloads

### ISSUE THREAD

**Issue by adevezin** [Storj/android-libstorj#13]
The storj download method `StorjAndroid.getInstance(mContext).downloadFile(...);` should have a parameter String filePath where filePath is the location you would like the file downloaded to. This will give users better control of their storj files.

**Comment by kaloyan-raev** [comment]
I have already implemented this in the java-libstorj binding: https://github.com/Storj/java-libstorj/commit/0eada95ad37d75e0a4c2cc62661e145b16356abc

It will become available in android-libstorj after refactor the project to depend on java-libstorj. I am currently working on this.

**Comment by kaloyan-raev** [comment]
Implemented in version 0.3.
