### ISSUE TITLE
Download Location for File Downloads

### ISSUE THREAD

**Issue by adevezin** [Storj/android-libstorj#18]
When downloading a file you allowed us to specify a download location. However when specifying this location the error "20021, Is a directory" is given. This seems to state that it is not looking for the download folder but instead the exact download folder with file name. So instead of "Downloads/Storj" it is looking for "Downloads/Storj/file.jpg". I understand this logic however it restricts devs to having to have a list of all storj files to download.

Is it possible to add a method that allows us to specify a default download location. Perhaps within the storj object. And then Storj can auto download the files like "LOCATION_SPECIFIED/BUCKET_NAME/FILE_NAME.EXTENSION"?

**Comment by kaloyan-raev** [comment]
Is this what you are looking for? https://github.com/Storj/java-libstorj/blob/master/src/main/java/io/storj/libstorj/Storj.java#L546

**Comment by adevezin** [comment]
Ahh thank you. I never saw that
