### ISSUE TITLE
JNI Crash [use of deleted global reference]

### ISSUE THREAD

**Issue by adevezin** [Storj/android-libstorj#19]
I am unsure what caused this crash. Just opened the application and it crashed with this error log:

https://pastebin.com/fg60qtAm

Happened a couple more times today. Seems to be the same but posting the link to crash just incase

https://pastebin.com/3pV1XiBk

**Comment by kaloyan-raev** [comment]
I haven't seen this myself. Is there any reliable way for reproducing it?

**Comment by adevezin** [comment]
It can be produced by running the 'upgrade...' branch in github.com/dri94/AllStorj.. However I think it has to do with having a global variable for Storj and it being accessed from a background and then foreground thread
