### ISSUE TITLE
Node stats

### ISSUE THREAD

**Issue by adevezin** [Storj/android-libstorj#21]
Are there any plans to add getting of managed node info from logged in account?

**Comment by kaloyan-raev** [comment]
Not sure what you mean? Could you explain in details?

**Comment by adevezin** [comment]
Apis to get the information here: https://docs.storj.io/docs/nodes-monitoring

**Comment by kaloyan-raev** [comment]
The libstorj native library does not provide API for this yet, but you can access the respective REST API directly from your app.

The endpoint is: https://api.storj.io/contacts

API documentation: https://storj.io/api.html. Look under `contacts`.

**Comment by adevezin** [comment]
Thanks, i will file an issue under libstorj to add this feature
