### ISSUE TITLE
Storj getBuckets() does not always call callback method

### ISSUE THREAD

**Issue by adevezin** [Storj/android-libstorj#25]
Sometimes  (usually the first time) i call getBuckets, it will not trigger any callback method. it will just hang. This will only really happen the first time. Then i will kill the app and reload, and it will trigger a callback method. This can be tested in the beta branch of github.com/dri94/AllStorj. Since the first time it happens, is after a user has logged in, it may have to do with something in the importKeys method (if it runs asynchronously under the hood, then that is most likely why).

**Comment by kaloyan-raev** [comment]
I fixed this recently in java-libstorj: https://github.com/Storj/java-libstorj/commit/e3305abc5f8ce5e8e96184b84372220185afb899

In the next days I will release new version of android-libstorj with the latest fixes from java-libstorj.

**Comment by kaloyan-raev** [comment]
I've just released version 0.7.1 of android-libstorj with the fix.
