### ISSUE TITLE
Storj error 6001 on login

### ISSUE THREAD

**Issue by dri94** [Storj/android-libstorj#26]
When trying to login into the application with an account i know is in good standing. I get a 6001 error. The password and email are the good (verified on the website), the mnemonic is different however.

Here is the code used to login that produces a 6001 error every time.

```
            var vKeys = -1
            try {
                vKeys = App.storjInstance!!.verifyKeys(Keys(params[0], params[1], params[2]))
                if (vKeys == Storj.NO_ERROR) {
                    App.storjInstance!!.importKeys(Keys(params[0], params[1], params[2]), "")
                }
            } catch (e: InterruptedException) {
                e.printStackTrace()
            }
```

**Comment by kaloyan-raev** [comment]
This is as expected: https://github.com/storj/java-libstorj/blob/master/src/main/java/io/storj/libstorj/Storj.java#L850

As you said, you call `verifyKeys()` with a mnemonic that is different than the one used to upload content to this account.

If you want to skip the check for the mnemonic then use the other `verifyKeys()` variant with just user and password: http://static.javadoc.io/io.storj/libstorj-java/0.8.3/io/storj/libstorj/Storj.html#verifyKeys-java.lang.String-java.lang.String-

**Comment by dri94** [comment]
Okay, i didn't realize using a different mnemonic would cause you to not be able to log in. Just thought you couldn't view the encrypted content.
