### ISSUE TITLE
keys == null

### ISSUE THREAD

**Issue by dri94** [Storj/android-libstorj#3]
In Storj.java we have checkKeys() which throws an exception if the keys are null. It might be better to call getKeys in this instance before having the exception thrown. When running in the background, keys are sometimes initially null even though the user has logged in. So by retrieving them and then throwing the error if they are null, we can be sure that in all instances the keys are truly not found

**Comment by kaloyan-raev** [comment]
Well... the `checkKeys()` method implementation does exactly what you are asking for, doesn't it? https://github.com/Storj/android-libstorj/blob/master/libstorj/src/main/java/io/storj/libstorj/Storj.java#L176-L180

**Comment by dri94** [comment]
Oh, i think i have an older version of your software. Did so many edits i cant use the gradle lol. Next time i will double check the code here. thanks
