### ISSUE TITLE
Request Failed with Status Code XXX

### ISSUE THREAD

**Issue by dri94** [Storj/android-libstorj#4]
When retreiving buckets or files I am getting errors sometimes. I get request failed with Status Code 500 and sometimes status code 0. What are these errors and are they something I am doing wrong?

**Comment by kaloyan-raev** [comment]
This error/status codes comes from the libstorj native library. If you get them occasionally then you most probably don't do anything wrong, but there is some problem with the Storj network.

I've seen status code 0 if the device has not internet connection at the moment.

Status code 500 should be an Internal Server Error on the Bridge.

For the 4-digit codes you can check here: https://github.com/Storj/libstorj/blob/master/src/storj.h#L51-L92

**Comment by dri94** [comment]
Okay thanks for the info and link
