### ISSUE TITLE
x86 and x86_64 support

### ISSUE THREAD

**Issue by dri94** [Storj/android-libstorj#5]
It would be great to have the library support x86 and x86_64. While this may seem like it only adds a small amount of physical devices, it would greatly help with other developers using this library. The arm emulator is very slow and the x86 is hugely beneficial in this area.

**Comment by kaloyan-raev** [comment]
Yes, I agree. The library should include the native libraries for all CPU architectures, or at least as many as possible. Initially, I focused only on armeabi-v7a, because libstorj has 6-7 dependencies and I could find them prebuild, or build them myself only for armeabi-v7a.

**Comment by dri94** [comment]
That definitely understandable. i guess we can just mark this as an enhancement?

**Comment by kaloyan-raev** [comment]
Sure. Once I have write permission to this repo, I will do it.

**Comment by kaloyan-raev** [comment]
This is now supported with version 0.4 of the library.
