### ISSUE TITLE
Import/Export of keys

### ISSUE THREAD

**Issue by dri94** [Storj/android-libstorj#8]
Just as crypto wallets are able to import and export keys. It would be great to have this in the storj library. So users can securely backup keys to an external location and import them again later. While this could be done on an app basis, since all Apps will have to use a mneomic, username, and password with your library, it would be better to have it standardized

**Comment by kaloyan-raev** [comment]
The API is already available: the `Storj` class has the `getKeys()` and `importKeys()` methods.

Could you describe in details what exactly you need in addition?

**Comment by dri94** [comment]
Does it have export keys? That's the main one that sounds be standardized
so encryption is the same throughout

**Comment by kaloyan-raev** [comment]
`getKeys()` exports the keys: https://github.com/Storj/android-libstorj/blob/master/libstorj/src/main/java/io/storj/libstorj/Storj.java#L69-L74
