### ISSUE TITLE
getBucketId on File

### ISSUE THREAD

**Issue by dri94** [Storj/android-libstorj#9]
If you wanted to display a list of all files this would be hard to distinguish which bucket it belongs too. By having the files have a bucket id parameter this could easily be worked around.

**Comment by kaloyan-raev** [comment]
The [Bridge API](https://storj.io/api.html) includes the bucket id in the file metadata, but [libstorj](https://github.com/Storj/libstorj) misses it in its [storj_file_meta_t](https://github.com/Storj/libstorj/blob/b9c3c40c7be75236fd1d5c06cdccc919f4f4e3b8/src/storj.h#L287-L299) structure. This should be easy to fix.

**Comment by dri94** [comment]
Awesome!

**Comment by kaloyan-raev** [comment]
https://github.com/Storj/libstorj/issues/407

**Comment by kaloyan-raev** [comment]
Implemented in version 0.3.
